-- V1: 初期スキーマ（KF-DD-003 テーブル設計書 v2.0）
-- Flyway が1度だけ実行する。以降の変更は V2__*.sql のように新しいファイルを追加する（このファイルは書き換えない）。
CREATE TABLE departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL,
  department_id BIGINT,
  manager_id BIGINT,
  hire_date DATE NOT NULL,
  status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
  failed_login_count INT DEFAULT 0 NOT NULL,
  locked_until TIMESTAMP,
  must_change_password BOOLEAN DEFAULT FALSE NOT NULL,
  password_changed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_users_department_id FOREIGN KEY (department_id) REFERENCES departments(id),
  CONSTRAINT fk_users_manager_id FOREIGN KEY (manager_id) REFERENCES users(id),
  CONSTRAINT uq_users_1 UNIQUE (email),
  CONSTRAINT ck_users_role CHECK (role IN ('EMPLOYEE','MANAGER','ADMIN')),
  CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE','INACTIVE'))
);
CREATE INDEX idx_users_manager ON users(manager_id);
CREATE INDEX idx_users_department ON users(department_id);

CREATE TABLE leave_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  legal_basis VARCHAR(100),
  is_paid BOOLEAN NOT NULL,
  max_days_rule VARCHAR(50),
  allow_half_day BOOLEAN NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_leave_types_1 UNIQUE (name),
  CONSTRAINT ck_lt_rule CHECK (max_days_rule IN ('LIMITED','UNLIMITED'))
);

CREATE TABLE leave_balances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  leave_type_id BIGINT NOT NULL,
  granted_days DECIMAL(4,1) NOT NULL,
  used_days DECIMAL(4,1) DEFAULT 0 NOT NULL,
  granted_on DATE NOT NULL,
  expires_on DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_leave_balances_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_leave_balances_leave_type_id FOREIGN KEY (leave_type_id) REFERENCES leave_types(id),
  CONSTRAINT uq_leave_balances_1 UNIQUE (user_id, leave_type_id, granted_on)
);
CREATE INDEX idx_lb_user ON leave_balances(user_id, leave_type_id);

CREATE TABLE attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  work_date DATE NOT NULL,
  clock_in TIMESTAMP,
  clock_out TIMESTAMP,
  work_minutes INT,
  overtime_minutes INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_attendance_records_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT uq_attendance_records_1 UNIQUE (user_id, work_date)
);
-- idx_att_user_date は uq_attendance_records_1 と同一列のため削除（冗長）

CREATE TABLE requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  request_type VARCHAR(20) NOT NULL,
  leave_type_id BIGINT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  unit VARCHAR(20),
  days DECIMAL(4,1),
  corrected_clock_in TIMESTAMP,
  corrected_clock_out TIMESTAMP,
  reason VARCHAR(200),
  status VARCHAR(20) NOT NULL,
  current_step INT NOT NULL,
  submitted_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_requests_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_requests_leave_type_id FOREIGN KEY (leave_type_id) REFERENCES leave_types(id),
  CONSTRAINT ck_req_type CHECK (request_type IN ('LEAVE','CLOCK_CORRECTION')),
  CONSTRAINT ck_req_status CHECK (status IN ('DRAFT','PENDING','RETURNED','REJECTED','APPROVED','WITHDRAWN')),
  CONSTRAINT ck_req_unit CHECK (unit IS NULL OR unit IN ('FULL','AM','PM'))
);
CREATE INDEX idx_req_user ON requests(user_id, status);
CREATE INDEX idx_req_period ON requests(user_id, start_date, end_date);

CREATE TABLE approval_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL,
  step_no INT NOT NULL,
  approver_id BIGINT,
  status VARCHAR(20) NOT NULL,
  comment VARCHAR(500),
  acted_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_approval_steps_request_id FOREIGN KEY (request_id) REFERENCES requests(id),
  CONSTRAINT fk_approval_steps_approver_id FOREIGN KEY (approver_id) REFERENCES users(id),
  CONSTRAINT uq_approval_steps_1 UNIQUE (request_id, step_no),
  CONSTRAINT ck_as_status CHECK (status IN ('WAITING','APPROVED','RETURNED','REJECTED')),
  CONSTRAINT ck_as_step CHECK (step_no IN (1,2))
);
CREATE INDEX idx_as_approver ON approval_steps(approver_id, status);

CREATE TABLE holidays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holiday_date DATE NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_holidays_1 UNIQUE (holiday_date)
);

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type VARCHAR(30),
  request_id BIGINT,
  message VARCHAR(500) NOT NULL,
  is_read BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_notifications_request_id FOREIGN KEY (request_id) REFERENCES requests(id)
);
CREATE INDEX idx_notif_user ON notifications(user_id, is_read);

-- updated_at 自動更新トリガ（全テーブル共通）
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_departments_updated_at BEFORE UPDATE ON departments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_leave_types_updated_at BEFORE UPDATE ON leave_types FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_leave_balances_updated_at BEFORE UPDATE ON leave_balances FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_attendance_records_updated_at BEFORE UPDATE ON attendance_records FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_requests_updated_at BEFORE UPDATE ON requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_approval_steps_updated_at BEFORE UPDATE ON approval_steps FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_holidays_updated_at BEFORE UPDATE ON holidays FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notifications_updated_at BEFORE UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 初期データ：休暇種別（法定休暇）
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('年次有給休暇','労働基準法第39条',TRUE,'LIMITED',TRUE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('産前休業','労働基準法第65条第1項',FALSE,'UNLIMITED',FALSE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('産後休業','労働基準法第65条第2項',FALSE,'UNLIMITED',FALSE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('生理休暇','労働基準法第68条',FALSE,'UNLIMITED',TRUE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('育児時間','労働基準法第67条',FALSE,'UNLIMITED',FALSE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('公民権行使の時間','労働基準法第7条',FALSE,'UNLIMITED',FALSE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('母性健康管理のための休暇','男女雇用機会均等法第12条',FALSE,'UNLIMITED',TRUE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('育児休業','育児・介護休業法第5条',FALSE,'UNLIMITED',FALSE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('子の看護等休暇','育児・介護休業法第16条の2',FALSE,'LIMITED',TRUE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('介護休暇','育児・介護休業法第16条の5',FALSE,'LIMITED',TRUE,TRUE);
INSERT INTO leave_types(name,legal_basis,is_paid,max_days_rule,allow_half_day,is_active) VALUES('介護休業','育児・介護休業法第11条',FALSE,'LIMITED',FALSE,TRUE);

-- 初期データ：部署（仮置き。実際の組織に合わせて管理画面／SQLで変更する）。ユーザーはアプリ側の初期化処理(DevDataInitializer)で作成
INSERT INTO departments(name) VALUES('管理部');
INSERT INTO departments(name) VALUES('システム開発事業部');
INSERT INTO departments(name) VALUES('ソリューション事業部');
INSERT INTO departments(name) VALUES('SAP事業部');
INSERT INTO departments(name) VALUES('クラウド基盤サービス部');
