-- V4: 休憩・日中離席の打刻。1日（attendance_records の1行）に複数回記録できる。
--   kind = BREAK（休憩：昼休みなど。労基法34条の休憩）／ AWAY（日中離席：私用外出など。勤務時間から控除する）
--   end_at が NULL の行は「休憩中／離席中」。同じ勤務日で NULL の行は同時に1つまで（部分ユニーク索引）。
CREATE TABLE attendance_breaks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_record_id BIGINT NOT NULL,
  kind VARCHAR(10) NOT NULL,
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_attendance_breaks_record FOREIGN KEY (attendance_record_id) REFERENCES attendance_records(id),
  CONSTRAINT ck_attendance_breaks_kind CHECK (kind IN ('BREAK','AWAY')),
  CONSTRAINT ck_attendance_breaks_range CHECK (end_at IS NULL OR end_at >= start_at)
);
CREATE INDEX idx_attendance_breaks_record ON attendance_breaks(attendance_record_id);
CREATE UNIQUE INDEX uq_attendance_breaks_open ON attendance_breaks(attendance_record_id) WHERE end_at IS NULL;
CREATE TRIGGER trg_attendance_breaks_updated_at BEFORE UPDATE ON attendance_breaks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
